# Generated by Django 2.2 on 2019-04-17 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=200)),
                ('article_body', models.TextField()),
                ('article_like', models.PositiveIntegerField()),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('article_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogauth.UserProfileInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=5, unique=True)),
                ('category_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Question_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogcontent.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogcontent.Article')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogauth.UserProfileInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Article_Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogcontent.Article')),
                ('tag_id', models.ManyToManyField(to='blogcontent.Tags')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogcontent.Category'),
        ),
    ]
