# Generated by Django 2.2 on 2019-04-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcontent', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='catagory',
            field=models.CharField(choices=[('ART', 'ART'), ('BEAUTY', 'BEAUTY'), ('BOOKS', 'BOOKS'), ('CULTURE', 'CULTURE'), ('FICTION', 'FICTION'), ('FILM', 'FILM'), ('FOOD', 'FOOD'), ('GAMING', 'GAMING'), ('HUMOUR', 'HUMOUR'), ('MEDIUM', 'MEDIUM')], default='MEDIUM', max_length=25),
        ),
    ]
